config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenditures
  root 'expenditures#index'
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :expenditures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!


end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController

  def index
    @expenditures = Expenditure.where(user_id: current_user.id).order(purchase_date: :desc)

  end

  def new
    @expenditure = Expenditure.new
  end

  def create
    @expenditure = current_user.expenditures.build(expenditure_params)
    if @expenditure.save
      redirect_to expenditure_path(@expenditure)
    else
      redirect_to new_expenditure_path
    end
  end

  def show
    @expenditure = Expenditure.find(params[:id])
  end

  private
    def expenditure_params
      params.require(:expenditure).permit(:name, :price, :quantity, :purchase_date)
    end
end

app/views/expenditures/index.html.erb
<div class="container">
<h1>My Purchases</h1>

<table class="table table-striped">
  <tr>
    <th>
      Date
    </th>
    <th>
      Purchase
    </th>
    <th>
      Price
    </th>
    <th>
      Quantity
    </th>
    <th>
    </th>
  </tr>

  <% @expenditures.each do |expenditure| %>
    <tr>
      <td>
        <%= expenditure.purchase_date.to_date %>
      </td>
      <td>
        <%= expenditure.name %>
      </td>
      <td>
        R<%= expenditure.price %>
      </td>
      <td>
        <%= expenditure.quantity %>
      </td>
      <td>
        <%= link_to 'Expand', expenditure_path(expenditure) %>
      </td>
  <% end %>
</table>

<%= link_to 'Add Purchase', new_expenditure_path %>


</div>

app/views/expenditures/new.html.erb
<div class="container">

<h1>New Expenditure</h1>
<%= render 'form' %>

</div>

app/views/expenditures/show.html.erb
<div class="container">

<h1><%= @expenditure.name %></h1>
<p>
  Date: <%= @expenditure.purchase_date.to_date %><br>
  Price: R<%= @expenditure.price %><br>
  Quantity: <%= @expenditure.quantity %><br>
</p>

<%= link_to 'back', expenditures_path %>

</div>

app/views/layouts/_alerts.erb
<div class="container">

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

</div>

app/views/layouts/_nav.html.erb
<div class="container">

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IxY02s03Brubudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<%= render 'layouts/alerts' %>
<%= yield %>

</body>
</html>